"""add owner_id to machines

Revision ID: 0112a8845430
Revises: daed33666de9
Create Date: 2026-03-30 08:19:16.894878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0112a8845430'
down_revision: Union[str, Sequence[str], None] = 'daed33666de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_machines_owner_id'), 'machines', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'machines', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_index(op.f('ix_machines_owner_id'), table_name='machines')
    op.drop_column('machines', 'owner_id')
    # ### end Alembic commands ###
