"""add machine settings

Revision ID: 0936126d19ba
Revises: 602c0d92f81f
Create Date: 2026-04-03 08:28:59.640821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0936126d19ba'
down_revision: Union[str, Sequence[str], None] = '602c0d92f81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_security_audit_logs_actor_machine_id'), table_name='security_audit_logs')
    op.drop_index(op.f('idx_security_audit_logs_actor_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('idx_security_audit_logs_created_at'), table_name='security_audit_logs')
    op.drop_index(op.f('idx_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('idx_security_audit_logs_success'), table_name='security_audit_logs')
    op.drop_index(op.f('idx_security_audit_logs_target_machine_id'), table_name='security_audit_logs')
    op.create_index(op.f('ix_security_audit_logs_actor_machine_id'), 'security_audit_logs', ['actor_machine_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_actor_type'), 'security_audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_actor_user_id'), 'security_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_created_at'), 'security_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_ip_address'), 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_severity'), 'security_audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_success'), 'security_audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_target_machine_id'), 'security_audit_logs', ['target_machine_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_target_user_id'), 'security_audit_logs', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_logs_target_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_target_machine_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_success'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_severity'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_ip_address'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_created_at'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_actor_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_actor_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_actor_machine_id'), table_name='security_audit_logs')
    op.create_index(op.f('idx_security_audit_logs_target_machine_id'), 'security_audit_logs', ['target_machine_id'], unique=False)
    op.create_index(op.f('idx_security_audit_logs_success'), 'security_audit_logs', ['success'], unique=False)
    op.create_index(op.f('idx_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_security_audit_logs_created_at'), 'security_audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_security_audit_logs_actor_user_id'), 'security_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('idx_security_audit_logs_actor_machine_id'), 'security_audit_logs', ['actor_machine_id'], unique=False)
    # ### end Alembic commands ###
