"""add machine settings

Revision ID: 31d28043277b
Revises: 0936126d19ba
Create Date: 2026-04-03 08:30:19.319744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d28043277b'
down_revision: Union[str, Sequence[str], None] = '0936126d19ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'machine_settings',
        sa.Column('machine_id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('domain', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('cloudflare_login', sa.String(length=255), nullable=True),
        sa.Column('cloudflare_api_key', sa.String(length=255), nullable=True),
        sa.Column('oauth_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('oauth_client', sa.String(length=255), nullable=True),
        sa.Column('oauth_secret', sa.String(length=255), nullable=True),
        sa.Column('oauth_mail', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('machine_id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_settings')
    # ### end Alembic commands ###
