"""add machine hostname and agent version

Revision ID: 6f54d7d98e5b
Revises: 77d5f70d4535
Create Date: 2026-03-29 11:07:09.665018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f54d7d98e5b'
down_revision: Union[str, Sequence[str], None] = '77d5f70d4535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('machines', sa.Column('agent_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'agent_version')
    op.drop_column('machines', 'hostname')
    # ### end Alembic commands ###
