"""add machine auth token fields

Revision ID: 77d5f70d4535
Revises: f118d36486e9
Create Date: 2026-03-29 10:54:40.848332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d5f70d4535'
down_revision: Union[str, Sequence[str], None] = 'f118d36486e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('auth_token_hash', sa.String(length=64), nullable=True))
    op.add_column('machines', sa.Column('auth_token_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('machines', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_machines_auth_token_hash'), 'machines', ['auth_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_auth_token_hash'), table_name='machines')
    op.drop_column('machines', 'last_seen_at')
    op.drop_column('machines', 'auth_token_created_at')
    op.drop_column('machines', 'auth_token_hash')
    # ### end Alembic commands ###
