"""create machines and pairing tokens

Revision ID: f118d36486e9
Revises: 
Create Date: 2026-03-29 10:38:33.661140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f118d36486e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_uuid')
    )
    op.create_table('pairing_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_tokens_expires_at'), 'pairing_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pairing_tokens_machine_id'), 'pairing_tokens', ['machine_id'], unique=False)
    op.create_index(op.f('ix_pairing_tokens_token_hash'), 'pairing_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairing_tokens_token_hash'), table_name='pairing_tokens')
    op.drop_index(op.f('ix_pairing_tokens_machine_id'), table_name='pairing_tokens')
    op.drop_index(op.f('ix_pairing_tokens_expires_at'), table_name='pairing_tokens')
    op.drop_table('pairing_tokens')
    op.drop_table('machines')
    # ### end Alembic commands ###
